# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - refs/tags/*
stages:
  - stage: Build
    jobs:
      - job: install_build_rust_linux_macos
        displayName: "build on linux and mac"
        strategy:
          matrix:
            - linux-64
                IMAGE_NAME: "ubuntu-latest"
                RUST_TOOLCHAIN: "x86_64-unknown-linux-musl"
            - linux-32
                IMAGE_NAME: "ubuntu-latest"
                RUST_TOOLCHAIN: "i686-unknown-linux-musl"
            - macos-64 
                IMAGE_NAME: "macOS-10.14"
                RUST_TOOLCHAIN: "x86_64-unknown-apple-darwin"
            - macos-32
                IMAGE_NAME: "macOS-10.14"
                RUST_TOOLCHAIN: "i686-unknown-apple-darwin"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain $RUST_TOOLCHAIN -y
            displayName: 'download and install rustup script'
          - script: "PATH=$PATH:$HOME/.cargo/bin cargo build --release"
            displayName: "cargo build"
          - publish: "$(System.DefaultWorkingDirectory)/target/release/idcfcli"
            artifact: "idcfcli_$(RUST_TOOLCHAIN)"
      - job: install_build_rust_windows
        displayName: "build on windows"
        matrix:
          windows-64:
            RUST_TOOLCHAIN: "x86_64-pc-windows-msvc"
          windows-32:
            RUST_TOOLCHAIN: "i686-pc-windows-msvc"
        pool:
          vmImage: windows-2019
        steps:
          - script: |
              curl -sSf -o rustup-init.exe https://win.rustup.rs
              rustup-init.exe -y --default-toolchain %RUST_TOOLCHAIN%
              set PATH=%PATH%;%USERPROFILE%\.cargo\bin
            displayName: "installing rustup"
          - script: "cargo build --release"
          - publish: "$(System.DefaultWorkingDirectory)/target/release/idcfcli.exe"
            artifact: idcfcli_exe_$(RUST_TOOLCHAIN)
          - publish: "$(System.DefaultWorkingDirectory)/target/release/idcfcli.pdb"
            artifact: idcfcli_exe_windows_pdb_$(RUST_TOOLCHAIN)
  - stage: Release
    condition: "startsWith(variables['Build.SourceBranch'], 'refs/tags/')"
    jobs:
      - job: github_release
        displayName: "Github Release"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - download: download_artifacts
            displayName: downloading artfifacts
            patterns: "**/idcfcli*"
          - task: GitHubRelease@0
            displayName: "releasing github"
            inputs:
              gitHubConnection: "idcfcli-github"
              action: create
              target: "$(Build.SourceVersion)"
              assets: "$(Pipeline.Workspace)/idcfcli*/**/*"
              isDraft: true

