[package]
name = "idcfcli"
version = "0.1.0"
authors = ["itn3000 <itn3000@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
clap = "2.33"
rust-crypto = "0.2"
percent-encoding = "2.0"
serde = "1.0"
serde_json = "1.0"
base64 = "0.10"
url = "2.0"
log = "0.4"
env_logger = "0.6"